WITH BA AS (
    SELECT
        BOOK.*,
        AUTHOR_NAME
    FROM
        BOOK
    JOIN
        AUTHOR
    ON
        AUTHOR.AUTHOR_ID = BOOK.AUTHOR_ID    
),
BI AS (
    SELECT
        BOOK_ID, 
        SUM(SALES) AS TOTAL_SALES
    FROM
        BOOK_SALES
    WHERE  
        SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
    GROUP BY
        BOOK_ID
)
SELECT
    BA.AUTHOR_ID,
    BA.AUTHOR_NAME,
    BA.CATEGORY,
    SUM(TOTAL_SALES * PRICE) AS TOTAL_SALES    
FROM
    BA
JOIN
    BI
ON
    BA.BOOK_ID = BI.BOOK_ID
GROUP BY
    AUTHOR_ID, CATEGORY
ORDER BY
    AUTHOR_ID ASC, CATEGORY DESC
