-- 코드를 입력하세요
SELECT
    PRODUCT_CODE, SUM(SALES_AMOUNT * PRICE) AS SALES
FROM
    OFFLINE_SALE, PRODUCT
WHERE
    OFFLINE_SALE.PRODUCT_ID = PRODUCT.PRODUCT_ID
GROUP BY
    PRODUCT_CODE
ORDER BY
    SALES DESC, PRODUCT_CODE ASC;