-- 코드를 작성해주세요
SELECT  
    ID,
    CASE 
        WHEN COLONY_NAME <= 0.25 THEN 'CRITICAL'
        WHEN COLONY_NAME <= 0.50 THEN 'HIGH'
        WHEN COLONY_NAME <= 0.75 THEN 'MEDIUM'
        WHEN COLONY_NAME <= 1 THEN 'LOW'
    END AS COLONY_NAME
FROM
    (SELECT
        ID,
        PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS COLONY_NAME
    FROM
        ECOLI_DATA
     ) AS E
ORDER BY
    ID ASC;