-- 코드를 입력하세요
SELECT    
    YEAR(SALES_DATE) -'0' AS YEAR,
    MONTH(SALES_DATE) -'0' AS MONTH,
    GENDER,
    COUNT(DISTINCT U.USER_ID)AS USERS
FROM
    ONLINE_SALE O
JOIN
    USER_INFO U
ON
    O.USER_ID = U.USER_ID
WHERE
    U.GENDER IS NOT NULL    
GROUP BY
    YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
ORDER BY
    YEAR ASC, MONTH ASC, GENDER ASC