# Clock, Reset
set_property -dict {PACKAGE_PIN R4 IOSTANDARD LVCMOS33} [get_ports clk]
set_property -dict {PACKAGE_PIN U7 IOSTANDARD LVCMOS33} [get_ports rstb]

# 7-Segment Pin Mapping (0-7)
#set_property -dict {PACKAGE_PIN U17  IOSTANDARD LVCMOS33} [get_ports {seg[0]}]
#set_property -dict {PACKAGE_PIN V17  IOSTANDARD LVCMOS33} [get_ports {seg[1]}]
#set_property -dict {PACKAGE_PIN W17  IOSTANDARD LVCMOS33} [get_ports {seg[2]}]
#set_property -dict {PACKAGE_PIN R18  IOSTANDARD LVCMOS33} [get_ports {seg[3]}]
#set_property -dict {PACKAGE_PIN T18  IOSTANDARD LVCMOS33} [get_ports {seg[4]}]
#set_property -dict {PACKAGE_PIN U18  IOSTANDARD LVCMOS33} [get_ports {seg[5]}]
#set_property -dict {PACKAGE_PIN V18  IOSTANDARD LVCMOS33} [get_ports {seg[6]}]
#set_property -dict {PACKAGE_PIN P19  IOSTANDARD LVCMOS33} [get_ports {seg[7]}]

# Digit Pin Mapping (0-7)
#set_property -dict {PACKAGE_PIN P14  IOSTANDARD LVCMOS33} [get_ports {digit[0]}]
#set_property -dict {PACKAGE_PIN R14  IOSTANDARD LVCMOS33} [get_ports {digit[1]}]
#set_property -dict {PACKAGE_PIN P15  IOSTANDARD LVCMOS33} [get_ports {digit[2]}]
#set_property -dict {PACKAGE_PIN P16  IOSTANDARD LVCMOS33} [get_ports {digit[3]}]
#set_property -dict {PACKAGE_PIN R16 IOSTANDARD LVCMOS33} [get_ports {digit[4]}]
#set_property -dict {PACKAGE_PIN N17 IOSTANDARD LVCMOS33} [get_ports {digit[5]}]
#set_property -dict {PACKAGE_PIN P17  IOSTANDARD LVCMOS33} [get_ports {digit[6]}]
#set_property -dict {PACKAGE_PIN R17 IOSTANDARD LVCMOS33} [get_ports {digit[7]}]

# LED Pin Mapping (0-15)
set_property -dict {PACKAGE_PIN Y18  IOSTANDARD LVCMOS33} [get_ports {LED[0]}]
#set_property -dict {PACKAGE_PIN AA18  IOSTANDARD LVCMOS33} [get_ports {LED[1]}]
#set_property -dict {PACKAGE_PIN AB18  IOSTANDARD LVCMOS33} [get_ports {LED[2]}]
#set_property -dict {PACKAGE_PIN W19  IOSTANDARD LVCMOS33} [get_ports {LED[3]}]
#set_property -dict {PACKAGE_PIN Y19  IOSTANDARD LVCMOS33} [get_ports {LED[4]}]
#set_property -dict {PACKAGE_PIN AA19  IOSTANDARD LVCMOS33} [get_ports {LED[5]}]
#set_property -dict {PACKAGE_PIN W20  IOSTANDARD LVCMOS33} [get_ports {LED[6]}]
#set_property -dict {PACKAGE_PIN AA20  IOSTANDARD LVCMOS33} [get_ports {LED[7]}]
#set_property -dict {PACKAGE_PIN AB20 IOSTANDARD LVCMOS33} [get_ports {LED[8]}]
#set_property -dict {PACKAGE_PIN W21 IOSTANDARD LVCMOS33} [get_ports {LED[9]}]
#set_property -dict {PACKAGE_PIN Y21  IOSTANDARD LVCMOS33} [get_ports {LED[10]}]
#set_property -dict {PACKAGE_PIN AA21  IOSTANDARD LVCMOS33} [get_ports {LED[11]}]
#set_property -dict {PACKAGE_PIN AB21  IOSTANDARD LVCMOS33} [get_ports {LED[12]}]
#set_property -dict {PACKAGE_PIN W22  IOSTANDARD LVCMOS33} [get_ports {LED[13]}]
#set_property -dict {PACKAGE_PIN Y22  IOSTANDARD LVCMOS33} [get_ports {LED[14]}]
#set_property -dict {PACKAGE_PIN AB22  IOSTANDARD LVCMOS33} [get_ports {LED[15]}]

## Push Switch Pin Mapping
#set_property -dict {PACKAGE_PIN M20  IOSTANDARD LVCMOS33} [get_ports PUSH_SW_UP]
set_property -dict {PACKAGE_PIN N20  IOSTANDARD LVCMOS33} [get_ports PUSH_SW_LEFT]
#set_property -dict {PACKAGE_PIN M21  IOSTANDARD LVCMOS33} [get_ports PUSH_SW_MID]
set_property -dict {PACKAGE_PIN M22  IOSTANDARD LVCMOS33}  [get_ports PUSH_SW_RIGHT]
#set_property -dict {PACKAGE_PIN N22  IOSTANDARD LVCMOS33}  [get_ports PUSH_SW_DOWN]

## Slide Switch Pin Mapping (0-15)
#set_property -dict {PACKAGE_PIN J4   IOSTANDARD LVCMOS15} [get_ports {DIP_SW[0]}]
#set_property -dict {PACKAGE_PIN L3   IOSTANDARD LVCMOS15} [get_ports {DIP_SW[1]}]
#set_property -dict {PACKAGE_PIN K3   IOSTANDARD LVCMOS15} [get_ports {DIP_SW[2]}]
#set_property -dict {PACKAGE_PIN M2   IOSTANDARD LVCMOS15} [get_ports {DIP_SW[3]}]
#set_property -dict {PACKAGE_PIN K6   IOSTANDARD LVCMOS15} [get_ports {DIP_SW[4]}]
#set_property -dict {PACKAGE_PIN J6   IOSTANDARD LVCMOS15} [get_ports {DIP_SW[5]}]
#set_property -dict {PACKAGE_PIN L5   IOSTANDARD LVCMOS15} [get_ports {DIP_SW[6]}]
#set_property -dict {PACKAGE_PIN L4   IOSTANDARD LVCMOS15} [get_ports {DIP_SW[7]}]
#set_property -dict {PACKAGE_PIN R19  IOSTANDARD LVCMOS33} [get_ports {DIP_SW[8]}]
#set_property -dict {PACKAGE_PIN V19 IOSTANDARD LVCMOS33} [get_ports {DIP_SW[9]}]
#set_property -dict {PACKAGE_PIN T20 IOSTANDARD LVCMOS33} [get_ports {DIP_SW[10]}]
#set_property -dict {PACKAGE_PIN U20 IOSTANDARD LVCMOS33} [get_ports {DIP_SW[11]}]
#set_property -dict {PACKAGE_PIN V20 IOSTANDARD LVCMOS33} [get_ports {DIP_SW[12]}]
#set_property -dict {PACKAGE_PIN T21 IOSTANDARD LVCMOS33} [get_ports {DIP_SW[13]}]
#set_property -dict {PACKAGE_PIN U21 IOSTANDARD LVCMOS33} [get_ports {DIP_SW[14]}]
#set_property -dict {PACKAGE_PIN V22 IOSTANDARD LVCMOS33} [get_ports {DIP_SW[15]}]
