-- 코드를 작성해주세요
SELECT
    ID,
    GENOTYPE,
    (SELECT GENOTYPE FROM ECOLI_DATA WHERE OED.PARENT_ID = ID) AS PARENT_GENOTYPE
FROM
    ECOLI_DATA OED
WHERE
        (SELECT GENOTYPE FROM ECOLI_DATA WHERE OED.PARENT_ID = ID)& GENOTYPE = (SELECT GENOTYPE FROM ECOLI_DATA WHERE OED.PARENT_ID = ID) 
ORDER BY
    ID ASC;
