SELECT
    OED.ID,
    OED.GENOTYPE,
    PARENT.GENOTYPE AS PARENT_GENOTYPE
FROM
    ECOLI_DATA OED
LEFT JOIN 
    ECOLI_DATA PARENT
ON 
    OED.PARENT_ID = PARENT.ID
WHERE
    PARENT.GENOTYPE IS NOT NULL
    AND (PARENT.GENOTYPE & OED.GENOTYPE) = PARENT.GENOTYPE
ORDER BY
    OED.ID ASC;
