WITH TOTAL_RENTALS AS (
    SELECT 
        CAR_ID,
        COUNT(*) AS TOTAL_RENTALS
    FROM 
        CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE 
        START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY 
        CAR_ID
    HAVING 
        TOTAL_RENTALS >= 5
)

SELECT 
    DATE_FORMAT(H.START_DATE, "%m") AS MONTH,
    H.CAR_ID,
    COUNT(*) AS RECORDS
FROM 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY H
JOIN 
    TOTAL_RENTALS T ON H.CAR_ID = T.CAR_ID
WHERE 
    H.START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY 
    MONTH, H.CAR_ID
HAVING 
    RECORDS > 0
ORDER BY 
    MONTH ASC, H.CAR_ID DESC;
