-- 코드를 작성해주세요
SELECT
    DP.ID, DP.EMAIL, DP.FIRST_NAME, DP.LAST_NAME
FROM
    DEVELOPERS DP
WHERE
    SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE NAME IN ('C#', 'PYTHON'))
    
ORDER BY
    DP.ID ASC