-- 코드를 입력하세요
SELECT 
    FIRST_HALF.FLAVOR 
FROM 
    FIRST_HALF, ICECREAM_INFO
WHERE 
    TOTAL_ORDER > 3000 AND
    FIRST_HALF.FLAVOR = ICECREAM_INFO.FLAVOR AND
    INGREDIENT_TYPE = 'FRUIT_BASED'    
ORDER BY
    TOTAL_ORDER DESC;