SELECT
    ID,
    FISH_NAME,
    LENGTH
FROM
    FISH_NAME_INFO OFNI
JOIN
    FISH_INFO FI
ON
    OFNI.FISH_TYPE = FI.FISH_TYPE
WHERE
    LENGTH = (SELECT MAX(FNI.LENGTH) FROM FISH_INFO FNI WHERE OFNI.FISH_TYPE = FNI.FISH_TYPE GROUP BY FNI.FISH_TYPE)
ORDER BY
    ID
