-- 코드를 작성해주세요
SELECT
    SUM(SCORE) AS SCORE, HE.EMP_NO, EMP_NAME, POSITION, EMAIL
FROM
    HR_EMPLOYEES HE
JOIN  
    HR_GRADE HG
ON
    HE.EMP_NO = HG.EMP_NO
JOIN
    HR_DEPARTMENT HD
ON
    HE.DEPT_ID = HD.DEPT_ID
GROUP BY
    HE.EMP_NO, EMP_NAME, POSITION, EMAIL
ORDER BY
    SCORE DESC
LIMIT 
    1