-- 코드를 입력하세요
SELECT
    CATEGORY,
    SUM(SALES) AS TOTAL_SALES
FROM
    BOOK_SALES
JOIN
    BOOK
ON 
    BOOK.BOOK_ID = BOOK_SALES.BOOK_ID
WHERE
    SALES_DATE LIKE "2022-01%"
GROUP BY
    CATEGORY
ORDER BY
    CATEGORY ASC;