-- 코드를 입력하세요
WITH FP AS(
    SELECT
        CATEGORY,
        MAX(PRICE) MPRICE
    FROM
        FOOD_PRODUCT
    GROUP BY
        CATEGORY
)
SELECT
    F.CATEGORY,
    PRICE AS MAX_PRICE,
    PRODUCT_NAME
FROM
    FOOD_PRODUCT F
JOIN
    FP
ON
    F.CATEGORY = FP.CATEGORY
WHERE
    PRICE = MPRICE AND F.CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY
    PRICE DESC;
    