-- 코드를 작성해주세요
WITH FIM AS (
    SELECT
        FISH_TYPE, IF(LENGTH IS NULL, 10, LENGTH) AS LENGTH
    FROM
        FISH_INFO
)
SELECT
    COUNT(*) AS FISH_COUNT,
    MAX(LENGTH) AS MAX_LENGTH,
    FISH_TYPE
FROM
    FIM
GROUP BY
    FISH_TYPE
HAVING
    AVG(LENGTH) >= 33
ORDER BY
    FISH_TYPE ASC;